name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Import and Trust GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private.key
          gpg --batch --import private.key
          rm private.key
          gpg --list-secret-keys --keyid-format LONG
          KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons --fingerprint | awk -F: '/^fpr:/ {print $10}' | head -n1)
          echo "$KEY_FINGERPRINT:6:" | gpg --batch --import-ownertrust

      - name: Install dependencies
        run: |
          make sources

      - name: Build the project
        run: |
          make build

      - name: Run unit and integration tests
        run: |
          make test

      - name: Package the library
        run: |
          make package

      - name: Installs the library
        run: |
          make install
